[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "stock_market_lstm"
version = "0.1.0"
requires-python = ">=3.11"
description = "LSTM-based stock price prediction. Give it a CSV, get predictions."
authors = [
  { name = "Mark Baltachi" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]

dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "scikit-learn",
    "tensorflow",
    "loguru",
    "python-dotenv",
    "tqdm",
    "typer",
]

[project.optional-dependencies]
dev = [
    "ipython",
    "jupyterlab",
    "notebook",
    "pytest",
    "ruff",
]

# This creates the 'stock-predict' terminal command
[project.scripts]
stock-predict = "stock_market_lstm.cli:app"

[tool.ruff]
line-length = 99
src = ["stock_market_lstm"]
include = ["pyproject.toml", "stock_market_lstm/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
known-first-party = ["stock_market_lstm"]
force-sort-within-sections = true